### ISSUE TITLE
how it work with nav-right

### ISSUE THREAD

**Issue by abhilashrajrs** [skywalkapps/bootstrap-notifications#2]
I tried to use it on nav-right it adding extra space to the page. I have attached a screenshot of it
![screenshot - google chrome 2017-01-04 12 00 04](https://cloud.githubusercontent.com/assets/1867079/21633459/6ca42b66-d275-11e6-8cf5-bcc1e1456880.png)

can u help me to fix it

**Comment by mumairofficial** [comment]
Add following two bootstrap classes to**dropdown-container**

`dropdown-menu dropdown-menu-right`

**Comment by JointKush** [comment]
Or change `.dropdown-container` to this 

```
.dropdown-container {
    position: absolute;
    top: 100%;
    right: 0;
    z-index: 1000;
    display: none;
    float: right;
    min-width: 200px;
    max-width: 330px;
    margin: 2px 0 0;
    list-style: none;
    font-size: 14px;
    background-color: #fff;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
}
```
![7ffa7ce03bbd473bb5cf3979e368261a](https://cloud.githubusercontent.com/assets/26471704/26748260/1d37cf9a-47ca-11e7-9575-66a6b0c64505.png)

**Comment by skywalkapps** [comment]
Hey guys! I have added new section to the docs concerning alignment options. http://skywalkapps.github.io/bootstrap-notifications/#alignment-options. Bootstrap Notifications extends another plugin Bootstrap Dropmenu, which has these capabilities. If you want to align notifications to the right, just add `.dropdown-position-bottomright` to the `.dropdown-container` and that's it!
