### ISSUE TITLE
Dependency on jquery 2.0.0

### ISSUE THREAD

**Issue by izzyu91** [skywalkapps/bootstrap-notifications#4]
Hi,

this package has a dependency for jquery ~2.0.0 but uses next to no javascript on its own. Couldn't this dependency be dropped as it is pulled in by the bootstrap dependency?

**Comment by skywalkapps** [comment]
Hi @izzyu91,
yes, you are right. It probably can be dropped. I will release it as a bug fix... Thanks!

**Comment by skywalkapps** [comment]
Just released v1.0.2 with removed jquery
