### ISSUE TITLE
Bootstrap 4.0

### ISSUE THREAD

**Issue by hesham** [skywalkapps/bootstrap-notifications#6]
Any plans to support bootstrap 4.0?

**Comment by skywalkapps** [comment]
Hi hesham,
Yes indeed, I am already working on it. I can't say exactly when, but hopefully soon.

**Comment by skywalkapps** [comment]
Hi hesham,
I have release first version for Bootstrap v4... you can check it out at http://skywalkapps.github.io/bootstrap-notifications/2.0/... it is still rather alpha, but it works

**Comment by hesham** [comment]
@skywalkapps great, thanks! i'll test it out :)

**Comment by matmiranda** [comment]
The link is off the air:

https://codeload.github.com/skywalkapps/bootstrap-notifications/zip/bootstrap-v4

**Comment by matmiranda** [comment]
@skywalkapps and @hesham please see this link:

https://github.com/skywalkapps/bootstrap-notifications/issues/9
